"""initial_migration

Revision ID: 5a2fbe28f194
Revises: 
Create Date: 2026-07-10 03:52:15.918762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a2fbe28f194'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cctv_cameras',
    sa.Column('cctv_id', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('area_name', sa.String(length=100), nullable=False),
    sa.Column('road_name', sa.String(length=150), nullable=False),
    sa.Column('camera_status', sa.String(length=50), nullable=False),
    sa.Column('coverage_radius', sa.Float(), nullable=False),
    sa.Column('installation_date', sa.Date(), nullable=True),
    sa.Column('owner', sa.String(length=50), nullable=False),
    sa.CheckConstraint("camera_status IN ('Working', 'Faulty')", name='check_cctv_status'),
    sa.CheckConstraint('latitude BETWEEN -90.0 AND 90.0', name='check_cctv_latitude'),
    sa.CheckConstraint('longitude BETWEEN -180.0 AND 180.0', name='check_cctv_longitude'),
    sa.PrimaryKeyConstraint('cctv_id')
    )
    op.create_table('hospitals',
    sa.Column('hospital_id', sa.String(length=50), nullable=False),
    sa.Column('hospital_name', sa.String(length=150), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('emergency_available', sa.Boolean(), nullable=False),
    sa.Column('contact_number', sa.String(length=50), nullable=True),
    sa.Column('open_24x7', sa.Boolean(), nullable=False),
    sa.CheckConstraint('latitude BETWEEN -90.0 AND 90.0', name='check_hospital_latitude'),
    sa.CheckConstraint('longitude BETWEEN -180.0 AND 180.0', name='check_hospital_longitude'),
    sa.PrimaryKeyConstraint('hospital_id')
    )
    op.create_table('police_stations',
    sa.Column('station_id', sa.String(length=50), nullable=False),
    sa.Column('station_name', sa.String(length=150), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_number', sa.String(length=50), nullable=True),
    sa.Column('open_24x7', sa.Boolean(), nullable=False),
    sa.CheckConstraint('latitude BETWEEN -90.0 AND 90.0', name='check_police_latitude'),
    sa.CheckConstraint('longitude BETWEEN -180.0 AND 180.0', name='check_police_longitude'),
    sa.PrimaryKeyConstraint('station_id')
    )
    op.create_table('street_lights',
    sa.Column('light_id', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('area_name', sa.String(length=100), nullable=False),
    sa.Column('road_name', sa.String(length=150), nullable=False),
    sa.Column('light_status', sa.String(length=50), nullable=False),
    sa.Column('brightness_level', sa.String(length=50), nullable=False),
    sa.Column('installation_date', sa.Date(), nullable=True),
    sa.Column('last_maintenance', sa.Date(), nullable=True),
    sa.CheckConstraint("light_status IN ('Working', 'Faulty')", name='check_light_status'),
    sa.CheckConstraint('latitude BETWEEN -90.0 AND 90.0', name='check_light_latitude'),
    sa.CheckConstraint('longitude BETWEEN -180.0 AND 180.0', name='check_light_longitude'),
    sa.PrimaryKeyConstraint('light_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('community_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_reports_id'), 'community_reports', ['id'], unique=False)
    op.create_table('crime_records',
    sa.Column('crime_id', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('area_name', sa.String(length=100), nullable=False),
    sa.Column('road_name', sa.String(length=150), nullable=False),
    sa.Column('crime_type', sa.String(length=100), nullable=False),
    sa.Column('crime_severity', sa.String(length=50), nullable=False),
    sa.Column('crime_date', sa.Date(), nullable=False),
    sa.Column('crime_time', sa.Time(), nullable=False),
    sa.Column('victim_gender', sa.String(length=50), nullable=True),
    sa.Column('station_id', sa.String(length=50), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.CheckConstraint("crime_severity IN ('High', 'Medium', 'Low')", name='check_crime_severity'),
    sa.CheckConstraint('latitude BETWEEN -90.0 AND 90.0', name='check_crime_latitude'),
    sa.CheckConstraint('longitude BETWEEN -180.0 AND 180.0', name='check_crime_longitude'),
    sa.CheckConstraint('risk_score BETWEEN 0 AND 100', name='check_crime_risk_score'),
    sa.ForeignKeyConstraint(['station_id'], ['police_stations.station_id'], ),
    sa.PrimaryKeyConstraint('crime_id')
    )
    op.create_table('emergency_contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_contacts_id'), 'emergency_contacts', ['id'], unique=False)
    op.create_table('journey_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('origin_lat', sa.Float(), nullable=False),
    sa.Column('origin_lng', sa.Float(), nullable=False),
    sa.Column('dest_lat', sa.Float(), nullable=False),
    sa.Column('dest_lng', sa.Float(), nullable=False),
    sa.Column('safety_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('journey_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journey_history_id'), 'journey_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journey_history_id'), table_name='journey_history')
    op.drop_table('journey_history')
    op.drop_index(op.f('ix_emergency_contacts_id'), table_name='emergency_contacts')
    op.drop_table('emergency_contacts')
    op.drop_table('crime_records')
    op.drop_index(op.f('ix_community_reports_id'), table_name='community_reports')
    op.drop_table('community_reports')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('street_lights')
    op.drop_table('police_stations')
    op.drop_table('hospitals')
    op.drop_table('cctv_cameras')
    # ### end Alembic commands ###
